[package]
name = "stonemason"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nom = { version = "^7" }
pest = "^2"
pest_derive = "^2"

[dev-dependencies]
proptest = "^1"
lazy_static = "^1"
